### ISSUE TITLE
Placeholder Tab memory usage

### ISSUE THREAD

**Issue by MarioLover63** [VP-GAMES/Godot4LocalizationEditor#10]
Whenever I switch to the placeholders tab, Godot starts using multiple Gigabytes of Ram, and it froze several unrelated programs in the process

**Comment by git2013vb** [comment]
Confirmed even if it is slight different:
In my case the problem start when I try to activate it in plugin tab.
I also have several warnings like this one :
``` 
WARNING: res://addons/localization_editor/scenes/placeholders/LocalizationPlaceholdersKey.tscn:4 - ext_resource, invalid UUID: uid://caiapkr8oaqe6 - using text path instead: res://addons/localization_editor/icons/Del.svg
```
and other errors like: 
```
SCRIPT ERROR: Parse Error: Identifier "LocalizationManager" not declared in the current scope.
          at: GDScript::reload (res://addons/localization_example/Localization.gd:29)
```
But these errors I guess are related to inactive plugin?

**Comment by VP-GAMES** [comment]
Thank you for reporting the error. I will try to fix it in the next few days.

**Comment by 01010100010100100100100101000111** [comment]
Just been testing this, things seem fine in Beta 4, but Beta 5-10 it consumes all memory on start-up and again when clicking the placeholders tab.

Tried commenting a bunch of the init code around the placeholder scenes but didn't seem to make a diff. Just trying to compile the source at the min so maybe I can spot something, will report back if I find anything.

**Comment by 01010100010100100100100101000111** [comment]
Got to the bottom of it, basically the Array of locales in LocalizationLocalesList.gd is being created every time it's called, and part of the plugin calls it within a loop, so it creating _a lot_ of new objects. 

The PR is a breaking change as it's a constant Dictionary now, so can be accessed by doing "LocalizationLocalesList.Locales" rather than calling the old function.

Also updated the tests and removed a couple that where pointless with it now being a Dictionary, it also fixes the UID warnings pointed out by @MarioLover63 

All the tests are passing and I haven't seen any errors while messing in the editor.

Up to @VP-GAMES if he want's to go with this PR or try a different approach.  

Edit: Just to note this has been tested on Beta 10
